from typing import TypedDict, Any


class AgentState(TypedDict, total=False):

    # User's natural-language question
    user_query: str

    user_intent: str


    db_host: str
    db_port: str
    db_name: str
    db_user: str
    db_password: str

    # Database schema
    schema: dict[str, Any]

    # SQL generated by the LLM
    generated_sql: str

    # Result of SQL validation
    sql_valid: bool

    # Validation error/reason
    error: str

    # SQL execution result
    query_result: list

    retry_count: int

    max_retries: int

    # Final response
    final_answer: str