from node import validate_sql_node


schema = {
    "customers": {
        "columns": [
            {"name": "id"},
            {"name": "name"},
            {"name": "email"},
        ]
    },
    "orders": {
        "columns": [
            {"name": "id"},
            {"name": "customer_id"},
            {"name": "amount"},
            {"name": "order_date"},
        ]
    }
}


def test_self_healing():

    # ---------------------------------------------------------
    # STEP 1: Simulate bad SQL generated by the LLM
    # ---------------------------------------------------------

    bad_sql = """
    SELECT c.name, o.wrong_amount
    FROM customers c
    JOIN orders o
        ON c.id = o.customer_id
    """

    state = {
        "user_query": "Show customer names and their order amounts",
        "schema": schema,
        "generated_sql": bad_sql,
        "retry_count": 0,
        "max_retries": 2,
        "error": "",
    }

    print("\n" + "=" * 70)
    print("STEP 1 - BAD SQL")
    print("=" * 70)

    print(state["generated_sql"])

    # ---------------------------------------------------------
    # STEP 2: Validate bad SQL
    # ---------------------------------------------------------

    validation_result = validate_sql_node(state)

    print("VALID:", validation_result["sql_valid"])
    print("ERROR:", validation_result.get("error", ""))

    assert validation_result["sql_valid"] is False

    # Store validator error in state
    state["error"] = validation_result["error"]

    # ---------------------------------------------------------
    # STEP 3: Simulate SQL correction
    #
    # Normally fix_sql_node() + LLM would do this.
    # We manually provide the corrected SQL so that
    # no Gemini API call is required.
    # ---------------------------------------------------------

    corrected_sql = """
    SELECT c.name, o.amount
    FROM customers c
    JOIN orders o
        ON c.id = o.customer_id
    """

    state["generated_sql"] = corrected_sql
    state["retry_count"] += 1
    state["error"] = ""

    print("\n" + "=" * 70)
    print("STEP 2 - CORRECTED SQL")
    print("=" * 70)

    print(state["generated_sql"])

    # ---------------------------------------------------------
    # STEP 4: Validate corrected SQL again
    # ---------------------------------------------------------

    validation_result = validate_sql_node(state)

    print("VALID:", validation_result["sql_valid"])
    print("ERROR:", validation_result.get("error", ""))

    assert validation_result["sql_valid"] is True

    print("\n" + "=" * 70)
    print("SELF-HEALING TEST PASSED")
    print("=" * 70)

    print("Bad SQL was rejected.")
    print("Corrected SQL was accepted.")
    print("Retry count:", state["retry_count"])


if __name__ == "__main__":
    test_self_healing()